apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    access: proxy
    url: mysql:3306
    database: tuition
    user: root
    password: password
    readOnly: false
  - name: Postgres
    type: postgres
    url: postgres:5432
    user: grafana
    secureJsonData:
      password: 'grafana'
    jsonData:
      database: tuition
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 905 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false