# docker compose up -d
# docker compose down

# https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/

version: "3.8"
services:
  mysql:
    image: mysql:latest
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tuition
    ports:
      - '3306:3306'
      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=myusername=admin
      - GF_SECURITY_ADMIN_PASSWORD=mypassword=password
    #  - GF_SERVER_ROOT_URL=http://my.grafana.server/
    #  - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
     - '3000:3000'
    volumes:
     - 'grafana_storage:/var/lib/grafana'
     - ./grafana/:/etc/grafana/provisioning
volumes:
  grafana_storage: {}

  # Create mysql datasource