# docker compose up -d
# docker compose down

# https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - '3000:3000'
    # environment:
    #   GF_AUTH_ANONYMOUS_ENABLED: true # Need to authorize anonymous users access to dashboards
    volumes:
      - ./grafana/:/etc/grafana/provisioning
    networks:
      - my_network

  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network: