# docker compose up -d
# docker compose down

# https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/

version: "3.9"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
     - '3000:3000'
    volumes:
    #  - 'grafana_storage:/var/lib/grafana'
     - ./grafana/:/etc/grafana/provisioning
    networks:
      - my_network
  
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tuition      
      MYSQL_USER: grafana
      MYSQL_PASSWORD: grafana
    ports:
      - '3306:3306'
    networks:
      - my_network
    # volumes:
    #   - mysql_storage

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: tuition
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana
    ports:
      - "5488:5432"
    networks:
      - my_network
      
# volumes:
#   grafana_storage:
    # mysql_storage: 

networks:
  my_network: