{
 "title": "Tuition",
 "time": { "from": "2008-01-01T00:00:00.000Z", "to": "2015-01-01T23:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "year",
    "label": "Year",
    "query": "SELECT\n  \"Year\"\nFROM\n  tuition\nGROUP BY\n  \"Year\"\nORDER BY\n  \"Year\" ASC"
   },
   {
    "name": "sector",
    "label": "Sector",
    "query": "SELECT\n  \"Sector Name\"\nFROM\n  tuition\nGROUP BY\n  \"Sector Name\"\nORDER BY\n  \"Sector Name\""
   },
   {
    "name": "state",
    "label": "State",
    "query": "SELECT\n  \"State\"\nFROM\n  tuition\nGROUP BY\n  \"State\"\nORDER BY\n  \"State\""
   },
   {
    "name": "institution",
    "label": "Institution",
    "query": "SELECT\n  \"Institution Name\"\nFROM\n  tuition\nGROUP BY\n  \"Institution Name\"\nORDER BY\n  \"Institution Name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Cost by Year",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"Year\", AVG(\"Cost\"), \"Predicted\" FROM tuition GROUP BY \"Year\", \"Predicted\" ORDER BY \"Year\" "
    }
   ]
  },
  {
   "title": "Cost by State: $state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT AVG(\"Cost\"), \"time\", \"State\" FROM tuition WHERE \"State\" IN ($state) GROUP BY \"time\", \"State\" ORDER BY \"time\" "
    }
   ]
  },
  {
   "title": "Cost by Sector : $sector",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT AVG(\"Cost\"), \"time\", \"Sector Name\" FROM tuition WHERE \"Sector Name\" IN ($sector) GROUP BY \"time\", \"Sector Name\" ORDER BY \"time\" "
    }
   ]
  }
 ]
}